# ============================================================
# STEP 4: REPORTS
# Query the database and generate reports
# ============================================================

import sqlite3
import pandas as pd
import os

DB_PATH = "output/sales_database.db"

def generate_reports():
    print("\n" + "=" * 50)
    print("STEP 4: GENERATING REPORTS")
    print("=" * 50)

    os.makedirs("reports", exist_ok=True)
    conn = sqlite3.connect(DB_PATH)

    # ── Report 1: Monthly Revenue ──────────────────────────
    monthly_query = """
        SELECT
            month,
            month_num,
            COUNT(order_id)             AS orders,
            ROUND(SUM(total_amount), 2) AS revenue
        FROM completed_orders
        GROUP BY month, month_num
        ORDER BY month_num
    """
    df_monthly = pd.read_sql_query(monthly_query, conn)
    df_monthly.drop(columns=["month_num"], inplace=True)

    # ── Report 2: Category Summary ─────────────────────────
    df_category = pd.read_sql_query("SELECT * FROM category_summary", conn)

    # ── Report 3: Top 5 Customers ──────────────────────────
    top_customers_query = """
        SELECT
            customer_name,
            COUNT(order_id)             AS orders,
            ROUND(SUM(total_amount), 2) AS total_spent
        FROM completed_orders
        GROUP BY customer_name
        ORDER BY total_spent DESC
        LIMIT 5
    """
    df_top = pd.read_sql_query(top_customers_query, conn)

    # ── Report 4: City-wise Revenue ────────────────────────
    city_query = """
        SELECT
            city,
            COUNT(order_id)             AS orders,
            ROUND(SUM(total_amount), 2) AS revenue
        FROM completed_orders
        GROUP BY city
        ORDER BY revenue DESC
    """
    df_city = pd.read_sql_query(city_query, conn)

    # ── Report 5: Order Status Breakdown ───────────────────
    status_query = """
        SELECT status, COUNT(*) AS count
        FROM orders
        GROUP BY status
    """
    df_status = pd.read_sql_query(status_query, conn)

    conn.close()

    # Total KPIs
    total_revenue  = df_monthly['revenue'].sum()
    total_orders   = df_monthly['orders'].sum()

    # ── Save CSV reports ───────────────────────────────────
    df_monthly.to_csv("reports/monthly_revenue.csv",   index=False)
    df_category.to_csv("reports/category_summary.csv", index=False)
    df_top.to_csv("reports/top_customers.csv",         index=False)
    df_city.to_csv("reports/city_revenue.csv",         index=False)
    print("✅ CSV reports saved in reports/ folder")

    # ── Generate HTML report ───────────────────────────────
    def df_to_html_table(df):
        rows = "".join(
            "<tr>" + "".join(f"<td>{v}</td>" for v in row) + "</tr>"
            for row in df.values
        )
        headers = "".join(f"<th>{c}</th>" for c in df.columns)
        return f"<table><thead><tr>{headers}</tr></thead><tbody>{rows}</tbody></table>"

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>ETL Sales Report</title>
<style>
  body {{ font-family: Arial, sans-serif; background: #f5f5f5; margin: 0; padding: 20px; }}
  h1 {{ color: #2c3e50; text-align: center; }}
  h2 {{ color: #34495e; border-left: 4px solid #3498db; padding-left: 10px; margin-top: 40px; }}
  .kpi-row {{ display: flex; gap: 20px; justify-content: center; margin: 30px 0; }}
  .kpi {{ background: white; border-radius: 10px; padding: 24px 40px;
          text-align: center; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }}
  .kpi .num {{ font-size: 32px; font-weight: bold; color: #2980b9; }}
  .kpi .label {{ font-size: 13px; color: #7f8c8d; margin-top: 4px; }}
  table {{ border-collapse: collapse; width: 100%; background: white;
           border-radius: 8px; overflow: hidden;
           box-shadow: 0 2px 8px rgba(0,0,0,0.06); }}
  th {{ background: #2c3e50; color: white; padding: 12px 16px; text-align: left; }}
  td {{ padding: 10px 16px; border-bottom: 1px solid #ecf0f1; }}
  tr:last-child td {{ border-bottom: none; }}
  tr:hover td {{ background: #f0f4f8; }}
  .section {{ background: white; border-radius: 10px; padding: 20px;
              margin-bottom: 30px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); }}
  .footer {{ text-align:center; color:#aaa; font-size:12px; margin-top:40px; }}
</style>
</head>
<body>
<h1>📊 ETL Sales Dashboard Report</h1>
<p style="text-align:center; color:#888;">Generated by Python ETL Pipeline</p>

<div class="kpi-row">
  <div class="kpi"><div class="num">₹{total_revenue:,.0f}</div><div class="label">Total Revenue</div></div>
  <div class="kpi"><div class="num">{int(total_orders)}</div><div class="label">Completed Orders</div></div>
  <div class="kpi"><div class="num">₹{total_revenue/total_orders:,.0f}</div><div class="label">Avg Order Value</div></div>
</div>

<div class="section">
<h2>📅 Monthly Revenue</h2>
{df_to_html_table(df_monthly)}
</div>

<div class="section">
<h2>🏷️ Category Summary</h2>
{df_to_html_table(df_category)}
</div>

<div class="section">
<h2>🏆 Top 5 Customers</h2>
{df_to_html_table(df_top)}
</div>

<div class="section">
<h2>🌆 City-wise Revenue</h2>
{df_to_html_table(df_city)}
</div>

<div class="section">
<h2>📌 Order Status Breakdown</h2>
{df_to_html_table(df_status)}
</div>

<div class="footer">ETL Pipeline Project · Python + Pandas + SQLite</div>
</body></html>"""

    with open("reports/sales_report.html", "w", encoding="utf-8") as f:
        f.write(html)
    print("✅ HTML report saved: reports/sales_report.html")

    # ── Print summaries to console ─────────────────────────
    print(f"\n💰 TOTAL REVENUE : ₹{total_revenue:,.2f}")
    print(f"📦 TOTAL ORDERS  : {int(total_orders)}")
    print("\n--- Monthly Revenue ---")
    print(df_monthly.to_string(index=False))
    print("\n--- Category Summary ---")
    print(df_category.to_string(index=False))
    print("\n--- Top 5 Customers ---")
    print(df_top.to_string(index=False))

if __name__ == "__main__":
    generate_reports()
